name: Build Python Server

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'client/assets/python/aichat/**'
      - '.github/workflows/build_python.yml'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'client/assets/python/aichat/**'
      - '.github/workflows/build_python.yml'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            cmake_args: '-DGGML_METAL=on -DGGML_BLAS=on -DGGML_BLAS_VENDOR=OpenBLAS'
          - os: windows-latest
            cmake_args: ''
          - os: ubuntu-latest
            cmake_args: ''

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.11'

    - name: Install Build Tools (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update -y && sudo apt-get install -y cmake ninja-build build-essential

    - name: Install Build Tools (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install cmake ninja openblas

    - name: Install Build Tools (Windows)
      if: matrix.os == 'windows-latest'
      run: choco install cmake ninja -y

    - name: Install Python Dependencies
      working-directory: client/assets/python/aichat
      run: pdm install --dev
      env:
        FORCE_CMAKE: "1"
        CMAKE_ARGS: ${{ matrix.cmake_args }}

    - name: Build with PyInstaller
      working-directory: client/assets/python/aichat
      run: pdm run pyinstaller -y main.spec

    - name: Upload Artifact (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: aichat-macos
        path: client/assets/python/aichat/dist/aichat

    # - name: Upload Artifact (Windows)
    #   if: matrix.os == 'windows-latest'
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: aichat-windows
    #     path: client/assets/python/aichat/dist/aichat.exe

    # - name: Upload Artifact (Linux)
    #   if: matrix.os == 'ubuntu-latest'
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: aichat-linux
    #     path: client/assets/python/aichat/dist/aichat
